# File di Configurazione:

# - percorso cartelle da osservare
# - percorso cartella backup
# - elenco cartelle da monitorare
#	In caso di modifica delle cartelle da monitorare, inserire i nomi uno dopo l'altro e mettere la  virgola.

# - percorso cartelle da osservare
path_cartella_da_osservare="C:\Work\marconilab"

# - percorso cartella backup
path_cartella_backup="C:\Work2\backup"

# - elenco cartelle da monitorare
sottocartelle_da_monitorare="clienti,preventivi,amministrazione"
