# File di Configurazione:

# - percorso cartelle da osservare
# - percorso cartella backup
# - elenco cartelle da monitorare
# - percorso file CSV
#	In caso di modifica delle cartelle da monitorare, inserire i nomi uno dopo l'altro e mettere la virgola.

# - percorso cartelle da osservare
path_cartella_da_osservare="C:\Tecnico"

# - percorso cartella backup
path_cartella_backup="d:\BakupAutomaticoConPythonMonitor\Tecnico"

# - elenco cartelle da monitorare
# sottocartelle_da_monitorare="clienti,preventivi,amministrazione"
sottocartelle_da_monitorare="*"

# - percorso file CSV con i dati degli eventi sui file
path_file_csv="../data/file.csv"

# - percorso logo visualizzato nella pagina web locale
#   Se il percorso è relativo, viene cercato nella cartella src.
#   Esempio: mettendo logo.png in src, usare path_logo_web="logo.png"
path_logo_web="logo.png"
